
version: "3.5"

services:
  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - db:db
    depends_on:
     - db
    ports:
     - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db
      PMA_PORT: ${MYSQL_PORT}

  db:
    # build: ./database
    image: mysql:5.7
    container_name: db
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}